### ISSUE TITLE
border effect with the vanilla-calendar-min.js

### ISSUE THREAD

**Issue by Titsta** [uvarov-frontend/vanilla-calendar#104] opened 2023-09-07 18:30 UTC
Hello, the minimified vanilla-calendar-min.js script can make some border-effect bugs with others scripts. ( it create somme global variables, and specialy a "b" variable. ) 
I correct the effect adding a simple auto-called function :
(function(){ ... all the code ... })();

( and thank you for your wonderfull code ! )

**Comment by uvarov-frontend** [comment] 2023-09-14 09:36
Hi, thanks for reporting the issue, it will be fixed in the next release.
The problem is identical to this #91

**Comment by uvarov-frontend** [comment] 2023-09-14 15:50
Fixed in v2.6.2

**Closed** 2023-09-14 15:51 UTC
Labels: bug
